version: '3.7'

services:

  bot:
    build: .
    container_name: bot
    volumes:
      - "./:/opt/app"
    restart: on-failure
    environment:
      ADMIN_CHAT_ID: ${ADMIN_CHAT_ID}
      DB_URL: ${DATABASE_url}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    env_file: 
      - ./.env

  db:
    image: postgres:11
    restart: on-failure
    container_name: reminder_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    env_file: 
      - ./.env